# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('fbeid', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
    ]
